spring:
  server:
    servlet:
      encoding:
        charset: UTF-8
        force: true
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true
  datasource:
    url: jdbc:h2:mem:testdb
    username: park
  h2:
    console:
      enabled: true








